const supportedBanks={
'BPD Aceh':'ACEH',
'BPD Aceh UUS':'ACEH_UUS',
'Bank Agris':'AGRIS',
'Bank BRI Agroniaga':'AGRONIAGA',
'Bank Amar Indonesia (formerly Anglomas International Bank)':'AMAR',
'Bank ANZ Indonesia':'ANZ',
'Bank Arta Niaga Kencana':'ARTA_NIAGA_KENCANA',
'Bank Artha Graha International':'ARTHA',
'Bank Artos Indonesia':'ARTOS',
'BPD Bali':'BALI',
'Bank of America Merill-Lynch':'BAML',
'Bangkok Bank':'BANGKOK',
'BPD Banten (formerly Bank Pundi Indonesia)':'BANTEN',
'Bank Central Asia (BCA)':'BCA',
'Bank Central Asia (BCA) Syariah':'BCA_SYR',
'BPD Bengkulu':'BENGKULU',
'Bank Bisnis Internasional':'BISNIS_INTERNASIONAL',
'Bank BJB':'BJB',
'Bank BJB Syariah':'BJB_SYR',
'Bank Negara Indonesia (BNI)':'BNI',
'Bank BNI Syariah':'BNI_SYR',
'Bank BNP Paribas':'BNP_PARIBAS',
'Bank of China (BOC)':'BOC',
'Bank Rakyat Indonesia (BRI)':'BRI',
'Bank Syariah BRI':'BRI_SYR',
'Bank Tabungan Negara (BTN)':'BTN',
'Bank Tabungan Negara (BTN) UUS':'BTN_UUS',
'BTPN Syariah (formerly Bank Sahabat Purba Danarta and Bank Tabungan Pensiunan Nasional UUS)':'BTPN_SYARIAH',
'Bank Bukopin':'BUKOPIN',
'Bank Syariah Bukopin':'BUKOPIN_SYR',
'Bank Bumi Arta':'BUMI_ARTA',
'Bank Capital Indonesia':'CAPITAL',
'China Construction Bank Indonesia (formerly Bank Antar Daerah and Bank Windu Kentjana International)':'CCB',
'Centratama Nasional Bank':'CENTRATAMA',
'Bank Chinatrust Indonesia':'CHINATRUST',
'Bank CIMB Niaga':'CIMB',
'Bank CIMB Niaga UUS':'CIMB_UUS',
'Citibank':'CITIBANK',
'Bank Commonwealth':'COMMONWEALTH',
'BPD Daerah Istimewa Yogyakarta (DIY)':'DAERAH_ISTIMEWA',
'BPD Daerah Istimewa Yogyakarta (DIY) UUS':'DAERAH_ISTIMEWA_UUS',
'Bank Danamon':'DANAMON',
'Bank Danamon UUS':'DANAMON_UUS',
'Bank DBS Indonesia':'DBS',
'Deutsche Bank':'DEUTSCHE',
'Bank Dinar Indonesia':'DINAR_INDONESIA',
'Bank DKI':'DKI',
'Bank DKI UUS':'DKI_UUS',
'Indonesia Eximbank (formerly Bank Ekspor Indonesia)':'EXIMBANK',
'Bank Fama International':'FAMA',
'Bank Ganesha':'GANESHA',
'Bank Hana':'HANA',
'Bank Harda Internasional':'HARDA_INTERNASIONAL',
'Hongkong and Shanghai Bank Corporation (HSBC) (formerly Bank Ekonomi Raharja)':'HSBC',
'Bank ICBC Indonesia':'ICBC',
'Bank Ina Perdania':'INA_PERDANA',
'Bank Index Selindo':'INDEX_SELINDO',
'Bank of India Indonesia':'INDIA',
'BPD Jambi':'JAMBI',
'BPD Jambi UUS':'JAMBI_UUS',
'Bank Jasa Jakarta':'JASA_JAKARTA',
'BPD Jawa Tengah':'JAWA_TENGAH',
'BPD Jawa Tengah UUS':'JAWA_TENGAH_UUS',
'BPD Jawa Timur':'JAWA_TIMUR',
'BPD Jawa Timur UUS':'JAWA_TIMUR_UUS',
'JP Morgan Chase Bank':'JPMORGAN',
'Bank JTrust Indonesia (formerly Bank Mutiara)':'JTRUST',
'BPD Kalimantan Barat':'KALIMANTAN_BARAT',
'BPD Kalimantan Barat UUS':'KALIMANTAN_BARAT_UUS',
'BPD Kalimantan Selatan':'KALIMANTAN_SELATAN',
'BPD Kalimantan Selatan UUS':'KALIMANTAN_SELATAN_UUS',
'BPD Kalimantan Tengah':'KALIMANTAN_TENGAH',
'BPD Kalimantan Timur':'KALIMANTAN_TIMUR',
'BPD Kalimantan Timur UUS':'KALIMANTAN_TIMUR_UUS',
'Bank Kesejahteraan Ekonomi':'KESEJAHTERAAN_EKONOMI',
'BPD Lampung':'LAMPUNG',
'BPD Maluku':'MALUKU',
'Bank Mandiri':'MANDIRI',
'Bank Syariah Mandiri':'MANDIRI_SYR',
'Mandiri Taspen Pos (formerly Bank Sinar Harapan Bali)':'MANDIRI_TASPEN',
'Bank Maspion Indonesia':'MASPION',
'Bank Mayapada International':'MAYAPADA',
'Bank Maybank (formerly BII)':'MAYBANK',
'Bank Maybank Syariah Indonesia':'MAYBANK_SYR',
'Bank Mayora':'MAYORA',
'Bank Mega':'MEGA',
'Bank Syariah Mega':'MEGA_SYR',
'Bank Mestika Dharma':'MESTIKA_DHARMA',
'Bank Mitra Niaga':'MITRA_NIAGA',
'Bank Sumitomo Mitsui Indonesia':'MITSUI',
'Bank Mizuho Indonesia':'MIZUHO',
'Bank MNC Internasional':'MNC_INTERNASIONAL',
'Bank Muamalat Indonesia':'MUAMALAT',
'Bank Multi Arta Sentosa':'MULTI_ARTA_SENTOSA',
'Bank Nationalnobu':'NATIONALNOBU',
'BPD Nusa Tenggara Barat':'NUSA_TENGGARA_BARAT',
'BPD Nusa Tenggara Barat UUS':'NUSA_TENGGARA_BARAT_UUS',
'BPD Nusa Tenggara Timur':'NUSA_TENGGARA_TIMUR',
'Bank Nusantara Parahyangan':'NUSANTARA_PARAHYANGAN',
'Bank OCBC NISP':'OCBC',
'Bank OCBC NISP UUS':'OCBC_UUS',
'Bank Oke Indonesia (formerly Bank Andara)':'OKE',
'Bank Panin':'PANIN',
'Bank Panin Syariah':'PANIN_SYR',
'BPD Papua':'PAPUA',
'Bank Permata':'PERMATA',
'Bank Permata UUS':'PERMATA_UUS',
'Prima Master Bank':'PRIMA_MASTER',
'Bank QNB Indonesia (formerly Bank QNB Kesawan)':'QNB_INDONESIA',
'Bank Rabobank International Indonesia':'RABOBANK',
'Royal Bank of Scotland (RBS)':'RBS',
'Bank Resona Perdania':'RESONA',
'BPD Riau Dan Kepri':'RIAU_DAN_KEPRI',
'BPD Riau Dan Kepri UUS':'RIAU_DAN_KEPRI_UUS',
'Bank Royal Indonesia':'ROYAL',
'Bank Sahabat Sampoerna':'SAHABAT_SAMPOERNA',
'Bank SBI Indonesia':'SBI_INDONESIA',
'Bank Shinhan Indonesia (formerly Bank Metro Express)':'SHINHAN',
'Sinarmas':'SINARMAS',
'Bank Sinarmas UUS':'SINARMAS_UUS',
'Standard Charted Bank':'STANDARD_CHARTERED',
'BPD Sulawesi Tengah':'SULAWESI',
'BPD Sulawesi Tenggara':'SULAWESI_TENGGARA',
'BPD Sulselbar':'SULSELBAR',
'BPD Sulselbar UUS':'SULSELBAR_UUS',
'BPD Sulut':'SULUT',
'BPD Sumatera Barat':'SUMATERA_BARAT',
'BPD Sumatera Barat UUS':'SUMATERA_BARAT_UUS',
'BPD Sumsel Dan Babel':'SUMSEL_DAN_BABEL',
'BPD Sumsel Dan Babel UUS':'SUMSEL_DAN_BABEL_UUS',
'BPD Sumut':'SUMUT',
'BPD Sumut UUS':'SUMUT_UUS',
'Bank Tabungan Pensiunan Nasional':'TABUNGAN_PENSIUNAN_NASIONAL',
'Bank of Tokyo Mitsubishi UFJ':'TOKYO',
'Gopay':'GOPAY',
'OVO':'OVO',
'DANA':'DANA',
'LinkAja':'LINKAJA',
'Shopeepay':'SHOPEEPAY',
};
